### ISSUE TITLE
Gallery not setting Content-Type for thumbnails?

### ISSUE THREAD

**Issue by martinf55** [splittingred/Gallery#104]
Since the 1.2 release (specifically commit 741ec85 and the changeover to phpthumbof style code), it looks like Content-Type is not being set for Gallery thumbnails, so they are getting 'text/html' by default?

I think this is because the cache file output is now returned directly to the connector, bypassing galPhpThumb->output() and phpthumb->OutputThumbnail() which usually sets headers.

Is there a different way to get these set now?

Using MODx Revolution 2.0.8-pl (traditional) and Gallery 1.2.0-pl.

**Comment by pixelchutes** [comment]
I can confirm the same behavior in MODx 2.1.1-pl (same Gallery version) that thumbs are also being returned with "text/html".

Also, when Gallery thumb-URL is viewed directly in browser (Mac OS X / Firefox 4.0.1), the image is not shown (rather, the binary is)

```
�PNG  IHDR�� ....
```

However, when placed within an IMG tag, the thumbnail image is showing up as expected.
