### ISSUE TITLE
GalleryItem thumbQuality

### ISSUE THREAD

**Issue by Neon4eg** [splittingred/Gallery#106]
Sorry, in http://rtfm.modx.com/display/ADDON/Gallery.GalleryItem thumbQuality is not mentioned, so I though there is no such parameter

**Comment by anselmh** [comment]
Is this available in snippet or not? Can you specify or test out? If yes, tell me, so I can add to RTFM. If not set this as feature-request.

**Comment by Neon4eg** [comment]
Yes it`s available. You can delete this issue.
By the way you can add default snippet-parameters.

**Comment by anselmh** [comment]
> Yes it`s available. 
> added to RTFM.
> 
> You can delete this issue.
> I can't. @splittingred: Can be closed. Invalid.
> 
> By the way you can add default snippet-parameters.
> what do you mean by that?

**Comment by Neon4eg** [comment]
thumbQuality, imageQuality, imageZoomCrop, thumbZoomCrop, thumbWidth, thumbHeight, imageWidth, imageHeight can be set by default in GalleryItem snippet
