### ISSUE TITLE
Improve Drag & Drop image-load

### ISSUE THREAD

**Issue by anselmh** [splittingred/Gallery#108]
Hi,

when you drag & drop moving images in a gallery the whole page with thumbnails seems to be rendered again each time you change the order. It shouldn't as it's very confusing and takes long time to get the correct order.

See screencast with theses issues (both): http://screencast.com/t/c0q4LqBF

**Comment by Audio** [comment]
I agree that the page reloading dramatically reduces the effectiveness of image reordering.

By the way, you reported this issue in april, didn't you? https://github.com/splittingred/Gallery/issues/89

**Comment by anselmh** [comment]
Uhm… I did. Didn't found before so I started new one… anyway.

**Comment by joergwork** [comment]
Hi! 
I did the following:

in album.items.view.js I commented out the success listener:

```
,onSort: function(o) {
        MODx.Ajax.request({
            url: this.config.url
            ,params: {
                action: 'mgr/item/sort'
                ,album: this.config.album
                ,source: o.source.id
                ,target: o.target.id
            }
            /*,listeners: {
                'success':{fn:function(r) {
                    this.run();
                },scope:this}
            }*/
        });
```

and in ddview.js I added 3 lines to move the element:

```
,onNodeDrop : function(target, dd, e, data) {
        var targetNode = this.view.getRecord(target);
        var sourceNode = this.view.getRecord(data.nodes[0]);
        var targetElement = Ext.get(target); 
        var sourceElement = Ext.get(data.nodes[0]); 
        sourceElement.insertBefore(targetElement);
        this.view.fireEvent('sort',{
            target: targetNode
            ,source: sourceNode
            ,event: e
            ,dd: dd
        });
        return true;
    }
```

For me it works so far. 
I used the 2.2 branch from 22 Dec and modx 2.2rc2

**Comment by splittingred** [comment]
Great improvement. Thanks!
