### ISSUE TITLE
After update to 1.2.0-pl all images disappeared

### ISSUE THREAD

**Issue by Neon4eg** [splittingred/Gallery#110]
Albums are fine, all images are present, but not displayed in manager and in site frontend
Looks like phpthumb is not working
https://rapidshare.com/files/4217253461/error_log.txt

**Comment by Audio** [comment]
Same problem here. I had to change the value of `gallery.files_url` to `files/` to get phpthumb working.

MODx 2.1.1, Gallery 1.2.0-pl

**Comment by belbiy** [comment]
Same issue here. Connector.php returns this {"success":false,"message":"Access denied.","total":0,"data":[],"object":[]} 
I'm using MODx 2.1.1 and Gallery 1.2.0-pl

**Comment by roele** [comment]
Same issue here with 2.0.8pl. Any known workarounds?

**Comment by Jenzemann** [comment]
MODx 2.0.8 pl, Gallery 1.2.0-pl and the same issue here.

**Comment by roele** [comment]
is it possible to go back to a previous version somehow?

**Comment by splittingred** [comment]
I can't replicate this at all, guys. Tried with Gallery 1.2.0-pl and Revo 2.0.8, 2.1.0, and 2.1.1; no problems.

**Comment by roele** [comment]
Update to 1.2.1 resolves the issue...

**Comment by Audio** [comment]
Yes, in 1.2.1 the problem is gone. Since it was problem with relative/absolute path, I think it was fixed by https://github.com/splittingred/Gallery/commit/4953a6eeedb30bbbf3a410d471eb6d0819d6030c#L2R62 (auto-prepend base path if not a URL).

Thanks :)
