### ISSUE TITLE
Images not showing up on website when upgrading from 1.2.0-pl to 1.2.1-pl

### ISSUE THREAD

**Issue by SebastienDaniel** [splittingred/Gallery#115]
I haven't investigated to find out "where" the problem was coming from, I only had two albums, so I re-uploaded them and everything worked fine from there.

Here's what happened:
I was running 1.2.0-pl
Setup my albums and a custom gallery image location
My albums were showing up perfectly on the website

Upgraded to 1.2.1-pl
Albums still existed
No images were showing up, all the links to the images seemed to have a "wrong path"
All image data and album data was stilled good in the gallery manager
Couldn't preview images in gallery manager either, another "wrong path" issue.

As previously stated, re-creating the albums fixed everything. So it's really an upgrade issue.

**Comment by Audio** [comment]
I think it's not an upgrade problem. File paths were set up wrong only in 1.2.0 (they were OK before and after Gallery v1.2.0). See https://github.com/splittingred/Gallery/issues/110

**Comment by ka8578** [comment]
I still have the same problem as mentioned above. Everything OK with Revo 2.1.0 and Gallery 1.2.0. 

After the upgrade to Revo 2.1.1.pl all images/thumbs not displayed. Gallery upgrade to 1.2.1. didn't help as well as Revo upgrade to 2.1.2. Recreating albums or even complete new installation (Revo and Gallery) - same situation. 

I posted this on the modx forum along with an error log (http://modxcms.com/forums/index.php/topic,60627.msg373673.html#new).

**Comment by ka8578** [comment]
problem solved with two changes in my webspace's script settings:

  PHP-allow_url_fopen     Off => On
  PHP-allow_url_include   Off => On

But with Revo 2.1.0/Gallery 1.2.0, the old script settings (off) worked fine. Hmm...
