### ISSUE TITLE
Galleryfic CSS parameter

### ISSUE THREAD

**Issue by tacticz** [splittingred/Gallery#116]
SUGGESTION

In model/gallery/plugins/galleriffic.class.php, changing line 91 (version 1.2.1),

from:
$this->modx->regClientCSS($this->gallery->config['assetsUrl'].'packages/galleriffic20/css/galleriffic-2.css');

to:
$this->modx->regClientCSS($this->gallery->config['assetsUrl'].'packages/galleriffic20/css/'.$this->modx->getOption('gallerifficCss',$this->config,'galleriffic-2.css'));

Would allow to use &galleryficCss parameter like:
[[!Gallery?
&album=`My Album`
&plugin=`galleriffic`
&gallerifficCss=`my_gallerific.css`]]

And let users have different Gallerific layouts in a website...

Regards

**Comment by coder4web** [comment]
Well, I need it too, thanks :)
