### ISSUE TITLE
Rebuilding Schema Breaks Gallery

### ISSUE THREAD

**Issue by AugmentBLU** [splittingred/Gallery#117]
Hi there,

I wanted to rebuild the schema files in Gallery and doing so had broken the Gallery.  I deleted only the files in the mysql folder and ran the build, all files were regenerated and the Gallery does load.  When clicking through to an album the thumbs do not appear, most of the details are in the JSON but not the information required for the thumbnails.  It just appears as NULL for all the thumb options.  When simply replacing all the files in the mysql folder with the default ones again the thumbs appear.

Further investigation shows the the galItem.class.php file in the default install has a lot of code for thumb generation but is not replicated when rebuilding the schema.  Is there a way to auto include that info or is this a manual process only?

Thanks

**Comment by splittingred** [comment]
Why would you rebuild the schema?

Secondly, you should _never_ delete files - the schema will regenerate the maps itself.
