### ISSUE TITLE
Feature request: "left-click" should do "Update Album"

### ISSUE THREAD

**Issue by eerne** [splittingred/Gallery#12]
Currently (modx 2.0.0 pl and gallery 1.0.0 rc1) you have to "right click" an album and choose "Update Album" to edit. There is currently no action on "left click" except that the background color changes. Could "Update Album" be the default "left-click" action?

**Comment by Kleist** [comment]
I agree on this one. It seems weird that left click doesn't do anything.

**Comment by gemweb** [comment]
I also agree. The default action (left click) could be to open the gallery, with right click menu for secondary actions.
