### ISSUE TITLE
Set (or Get) Published Date of Gallery

### ISSUE THREAD

**Issue by ghost** [splittingred/Gallery#125]
I'm new to Gallery and am trying to find a way to display and sort by the published date of a Gallery.  Is this data stored on the gallery?  If not, can it be added in a future release?

**Comment by Mark-H** [comment]
Try sorting on "createdon"

All fields are in the schema: https://github.com/splittingred/Gallery/blob/develop/core/components/gallery/model/schema/gallery.mysql.schema.xml
