### ISSUE TITLE
Gallery thumbProperties multiple fltr[] options

### ISSUE THREAD

**Issue by paulkoan** [splittingred/Gallery#132]
Version: gallery-1.2.2-pl

JSON and PHP arrays don't support multiple keys with the same name, so multiple fltr rules aren't passed through to phpThumb via thumbProperties.

Just the last fltr is applied:

`&thumbProperties=`{"fltr[]": "ric|5|5","fltr[]": "bord|1|5|5|909090"}`  =>  &fltr[]=bord|1|5|5|909090`

It looks like a separate parameter might be needed to handle fltr as a special case.

**Comment by Mark-H** [comment]
Didn't try, but what about this?

&thumbProperties=`{"fltr[]": "ric|5|5,bord|1|5|5|909090"}`

**Comment by Mark-H** [comment]
Or actually, as it's a JSON object, this would probably be better:

&thumbProperties={"fltr[]": {"ric|5|5","bord|1|5|5|909090"} }

**Comment by splittingred** [comment]
<pre>
&thumbProperties=`{"fltr":["wmt|text|2|C|AAAAAA","ric|5|5"]}`
</pre>
