### ISSUE TITLE
Feature: display random image

### ISSUE THREAD

**Issue by warenhaus** [splittingred/Gallery#142]
in this thread the displaying of a random image, taken from an album (or even from a random album) is requested:
http://forums.modx.com/index.php/topic,52717.msg369684.html#msg369684

the solutions don't seem to work, neither does the one mentioned in (closed) issue #33.

I would like to see this feature, too.

**Comment by Mark-H** [comment]
&sort=`RAND()` should do the trick?

**Comment by splittingred** [comment]
&sort=`rand` will work
