### ISSUE TITLE
Gallery breaks when entering a URL with a ? in it

### ISSUE THREAD

**Issue by jacobkball** [splittingred/Gallery#147]
Entering the following string:

http://www.jofra.com/UK/Products/Temperature_calibrators.aspx?ProductID=PROD17&m=ecom_catalog

in the URL field for a gallery item causes the whole gallery to not display at all.

If the URL is changed to remove the ? for the query string, the gallery displays correctly.

**Comment by jacobkball** [comment]
I have since discovered that if you enter '& # 63 ;' (minus the spaces) in the URL string where the ? is supposed to be, it will work.

**Comment by splittingred** [comment]
I can't replicate this at all. Can you give more implementation information?

**Comment by jacobkball** [comment]
I'd say this has been resolved in later versions of Gallery (or MODX itself), as I can't replicate it now either using 2.2.2, with Gallery 1.5.0pl.
