### ISSUE TITLE
Sort order field for albums

### ISSUE THREAD

**Issue by kenquad** [splittingred/Gallery#148]
When displaying albums, it would be nice if we could specify a particular order in which to display them other than by create date, much the like the "menu order" of resources.

**Comment by Mark-H** [comment]
From the docs at http://rtfm.modx.com/display/ADDON/Gallery.GalleryAlbums

sort    The field to sort the results by.

Fields: parent, name, description, createdon, createdby, rank (https://github.com/splittingred/Gallery/blob/develop/core/components/gallery/model/schema/gallery.mysql.schema.xml)

**Comment by kenquad** [comment]
Maybe I'm missing something horribly obvious here, but where, exactly, does one specify "rank"?  I see no such field in the update gallery window.

(Also, it would be nice if somebody would update the docs with the options for that field.)

**Comment by Mark-H** [comment]
You can just drag the resources in the gallery overview to change the "rank" order?

In your snippet you need to specify &sort=`rank` in your galleryAlbums snippet.

**Comment by kenquad** [comment]
That's beautiful.  It would be nice if the docs made it a bit more clear ;)

Thanks!
