### ISSUE TITLE
Manager pane is blank

### ISSUE THREAD

**Issue by rolandtom** [splittingred/Gallery#155]
When clicking Components / Gallery, the pane turns blank. Only the resources/elements/files trees are shown on the left.

modx 2.1.5
gallery 1.4.0-rc1
PHP 5.2.17-pl0-gentoo
MYSQL 5.1.56

Uninstalls with:

Finding package with signature: gallery-1.4.0-rc1
Package found. Preparing to uninstall.
xPDO->toCache() could not cache object with signature objects/modMenu/342e29d6b80e8ae93f69592e7ac64224
Removed modMenu instance with primary key gallery
xPDO->toCache() could not cache object with signature objects/modAction/4df8a8086d98d445a32e6953ee700032
Removed modAction instance with primary key 74
xPDO->toCache() could not cache object with signature objects/modCategoryClosure/5efac1b41dd5dbf1949a2c17dfe87b15
Removed modCategoryClosure instance with primary key Array ( [0] => 17 [1] => 17 )
xPDO->toCache() could not cache object with signature objects/modCategoryClosure/d41d8cd98f00b204e9800998ecf8427e
Removed modCategoryClosure instance with primary key Array ( [0] => 0 [1] => 17 )
xPDO->toCache() could not cache object with signature objects/modCategory/cbf6e2b72e403b12d7ee63a138f32647
Removed modCategory instance with primary key 17
xPDO->toCache() could not cache object with signature objects/modChunk/30d1a733d5782fba0d1ba6887657ef93
Removed modChunk instance with primary key 60
xPDO->toCache() could not cache object with signature objects/modChunk/0a07ae053417132a394b138d7e730171
Removed modChunk instance with primary key 61
xPDO->toCache() could not cache object with signature objects/modSnippet/09bc602d1fa3ff9ad3ab390b6500891f
Removed modSnippet instance with primary key 31
xPDO->toCache() could not cache object with signature objects/modSnippet/491181935f345c9d74f1cf6e4eeb8b4b
Removed modSnippet instance with primary key 32
xPDO->toCache() could not cache object with signature objects/modSnippet/729c39b09b14c7043d3432245f58fc08
Removed modSnippet instance with primary key 33
Removing files in file resolver: /var/www/users/johkho/wwwroot/website2011/assets/components/gallery
Removing files in file resolver: /var/www/users/johkho/wwwroot/website2011/core/components/gallery
xPDO->toCache() could not cache object with signature objects/modPluginEvent/76a7cdfbe9949e3e4208d014a73b124e
Removed modPluginEvent instance with primary key Array ( [0] => 8 [1] => OnDocFormPrerender )
xPDO->toCache() could not cache object with signature objects/modPluginEvent/d95b98e8fd886dd790ff3c890e0d3a2d
Removed modPluginEvent instance with primary key Array ( [0] => 8 [1] => OnTVInputPropertiesList )
xPDO->toCache() could not cache object with signature objects/modPluginEvent/974d2c7c592f7aaee4527003601c5f32
Removed modPluginEvent instance with primary key Array ( [0] => 8 [1] => OnTVInputRenderList )
xPDO->toCache() could not cache object with signature objects/modPluginEvent/6c3914ccf56cd285c57dfd69a1c3c297
Removed modPluginEvent instance with primary key Array ( [0] => 8 [1] => OnTVOutputRenderList )
xPDO->toCache() could not cache object with signature objects/modPluginEvent/7d384e7db11c55253512c51811d5f4f9
Removed modPluginEvent instance with primary key Array ( [0] => 8 [1] => OnTVOutputRenderPropertiesList )
xPDO->toCache() could not cache object with signature objects/modPlugin/99944bf07088f815a966d585daed6a7e
Removed modPlugin instance with primary key 8
Skipping modPluginEvent object (data object does not exist and cannot be removed): Array ( [pluginid] => 0 [event] => OnTVInputRenderList )
Skipping modPluginEvent object (data object does not exist and cannot be removed): Array ( [pluginid] => 0 [event] => OnTVInputPropertiesList )
Skipping modPluginEvent object (data object does not exist and cannot be removed): Array ( [pluginid] => 0 [event] => OnTVOutputRenderList )
Skipping modPluginEvent object (data object does not exist and cannot be removed): Array ( [pluginid] => 0 [event] => OnTVOutputRenderPropertiesList )
Skipping modPluginEvent object (data object does not exist and cannot be removed): Array ( [pluginid] => 0 [event] => OnDocFormPrerender )
xPDO->toCache() could not cache object with signature objects/modSystemSetting/a9bc63c320b33d5a4159cf42aa6fdc53
Removed modSystemSetting instance with primary key gallery.file_structure_version
xPDO->toCache() could not cache object with signature objects/modSystemSetting/4bf77241252c5d8be3586f77b8c9799f
Removed modSystemSetting instance with primary key gallery.phpthumb_url
xPDO->toCache() could not cache object with signature objects/modSystemSetting/92f329a2a633abbe3c316efa989379c8
Removed modSystemSetting instance with primary key gallery.files_url
xPDO->toCache() could not cache object with signature objects/modSystemSetting/ca1a910044addd023db8c9f503ff44cd
Removed modSystemSetting instance with primary key gallery.assets_path
xPDO->toCache() could not cache object with signature objects/modSystemSetting/3eb284650a6673fef9388984cea53b45
Removed modSystemSetting instance with primary key gallery.files_path
xPDO->toCache() could not cache object with signature objects/modSystemSetting/f4ebfa42ee3db1312f5a986ce1070a5d
Removed modSystemSetting instance with primary key gallery.phpthumb_path
xPDO->toCache() could not cache object with signature objects/modSystemSetting/e752c99f93ea8d4f46a7cbb04f7b95f9
Removed modSystemSetting instance with primary key gallery.assets_url
xPDO->toCache() could not cache object with signature objects/modSystemSetting/07a95c7fa3c6aed347126480ded5fcb8
Removed modSystemSetting instance with primary key gallery.tiny.theme_advanced_css_selectors
xPDO->toCache() could not cache object with signature objects/modSystemSetting/a17acee9a85d566631b7e5160af9529d
Removed modSystemSetting instance with primary key gallery.core_path
xPDO->toCache() could not cache object with signature objects/modSystemSetting/6bda343a77bce4391abcacaa303eeaed
Removed modSystemSetting instance with primary key gallery.tiny.theme_advanced_blockformats
xPDO->toCache() could not cache object with signature objects/modSystemSetting/cf560d626853a537360ab7eeb144f9fa
Removed modSystemSetting instance with primary key gallery.tiny.custom_plugins
xPDO->toCache() could not cache object with signature objects/modSystemSetting/95a97f4d1cc0829a03e19f8bcd9ac270
Removed modSystemSetting instance with primary key gallery.tiny.theme
xPDO->toCache() could not cache object with signature objects/modSystemSetting/0c80d812fe9bc46ad1b11b213d9f8570
Removed modSystemSetting instance with primary key gallery.tiny.buttons5
xPDO->toCache() could not cache object with signature objects/modSystemSetting/8a9142336a1fa03291c3fbd82e48cfd4
Removed modSystemSetting instance with primary key gallery.tiny.height
xPDO->toCache() could not cache object with signature objects/modSystemSetting/6f52afb8dfca1a2d4018134e16f86cd7
Removed modSystemSetting instance with primary key gallery.tiny.buttons1
xPDO->toCache() could not cache object with signature objects/modSystemSetting/63421f8d489c75a7128df12f3c531873
Removed modSystemSetting instance with primary key gallery.tiny.buttons2
xPDO->toCache() could not cache object with signature objects/modSystemSetting/6c45249a4c80d202c8aa88b92167f1e8
Removed modSystemSetting instance with primary key gallery.tiny.buttons4
xPDO->toCache() could not cache object with signature objects/modSystemSetting/c6f85dd1439a178aca225c36eba90032
Removed modSystemSetting instance with primary key gallery.tiny.buttons3
xPDO->toCache() could not cache object with signature objects/modSystemSetting/3f4505eac87446fb098628ba29b2f12e
Removed modSystemSetting instance with primary key gallery.tiny.width
xPDO->toCache() could not cache object with signature objects/modSystemSetting/ade90fdfc1a004f1b7c7a7bf6b977bd6
Removed modSystemSetting instance with primary key gallery.use_richtext
xPDO->toCache() could not cache object with signature objects/modSystemSetting/123222a3cb5db29238fdd9eb12b2fa9a
Removed modSystemSetting instance with primary key gallery.thumbs_prepend_site_url
xPDO->toCache() could not cache object with signature objects/modSystemSetting/830e0b54a077328db32324a3b65bdce7
Removed modSystemSetting instance with primary key gallery.default_batch_upload_path
xPDO->toCache() could not cache object with signature objects/modSystemSetting/0b76f9e79cab1f1d37cfacd916aef63a
Removed modSystemSetting instance with primary key gallery.backend_thumb_zoomcrop
xPDO->toCache() could not cache object with signature objects/modSystemSetting/89fd83423a8d2e881431094698dff211
Removed modSystemSetting instance with primary key gallery.backend_thumb_width
xPDO->toCache() could not cache object with signature objects/modSystemSetting/f4b40006cc6aba506b20d12aa2aa98fb
Removed modSystemSetting instance with primary key gallery.backend_thumb_height
xPDO->toCache() could not cache object with signature objects/modSystemSetting/06892c3afff78e9a4eba445640c1e45d
Removed modSystemSetting instance with primary key gallery.backend_thumb_far
xPDO->toCache() could not cache object with signature objects/modNamespace/342e29d6b80e8ae93f69592e7ac64224
Removed modNamespace instance with primary key gallery
Package successfully uninstalled with signature: gallery-1.4.0-rc1
modManagerLog: Attempt to set NOT NULL field item to NULL

And installs with:

Attempting to install package with signature: gallery-1.4.0-rc1
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => xhtml_urls )
Successfully installed package gallery-1.4.0-rc1

**Comment by rolandtom** [comment]
It was file permission related. I set 777 recursively to all gallery related folders and now it works. However, I still have issues with Gallery seemingly not being able to create folders in the 'files' subfolder, even if the whole 'assets' folder is now set to 777.

**Comment by splittingred** [comment]
This is likely a permissions issue with your server, not with Gallery. Make sure PHP has full access to write to the directories it needs.
