### ISSUE TITLE
Issues with 2.2.1

### ISSUE THREAD

**Issue by AugmentBLU** [splittingred/Gallery#188]
Hello,

I'm finding some issues with uploading and the thumbs being displayed in the backend.  

Multiple upload doesn't seem to work, it fails everytime when trying to upload... any idea what could be causing this?  Upload Item works fine.

Also, after uploading an image, the thumbnail displayed in the backend is the same as all previous images uploaded for this album.  The image on the frontend is correct though.  I have tried reinstalling Gallery after completely removing the package, removed the tables in the DB etc but this has not solved the issue.  I have tried emptying the following cache folders manually but without luck.

/core/cache/
/assets/components/gallery/cache

The connector seems to find the thumbnail even though I emptied the 2 cache folders above, they remain empty so is the thumbs being saved else where?

Having a closer look at the source, I uploaded 2 images and both have the same url so that's why all images show the same thumb in the backend.

/assets/components/gallery/connector.php?action=web/phpthumb&h=100&w=100&zc=1&far=C&src=%2Fassets%2Fgallery%2F1%2F1.jpg

For the record, I just downgraded to 1.4 and it's working as it should.  

Thanks,
Ross

**Comment by chunkyRice** [comment]
I encountered the same problem, but in my case downgrading didn't work. That means I'm (or rather my client is) stuck with a Gallery that won't allow for uploading any new images. I hope this can be solved soon. I would be very appreciative if it could.

**Comment by AugmentBLU** [comment]
This is issue is still happening with 2.2.2 and 1.5 rc1.  

Hopefully these issues can be sorted soon.

**Comment by janice171** [comment]
yes this is still happening with 2.2.2 and 1.5rc1.
1.4 does work with MODx 2.2.2 though.

I had to force removal of Gallery 1.5, and delete the modx_gallery... tables from the database, it was only then that i could get Gallery 1.4 to work with 2.2.2.

**Comment by philkirkman** [comment]
could someone possibly send me version 1.4 so i can downgrade? This issue has really stumped me.

**Comment by janice171** [comment]
Hi,

Yes sure, i've uploaded it here: ....
see below.

**Comment by thomasd** [comment]
@philkirkman: Note that you can always download all older versions of a modx-extra via modx.com/extras.
For Gallery: http://modx.com/extras/package/gallery -> "Prev. Versions"-Tab.

**Comment by wholein1** [comment]
hello, 

I want to say thank you to Janice for helping me look at this issue. I am using 2.1.0 Revo and 1.5 gallery loaded in by the package management. I have spent hours looking at this issue to say I ahve yet to resolve the issue with some of the suggestion offered in modx forums. But this is where I am at:
I can upload batch files and it adds images perfectly, but when it come to the single and multiple it adds the images, but it is a duplicate. I also know that if you upload single and it has a different file exstension that the previosu it will show correclty. The only configuration currently is setting the file_path and file_url in the system core to files/ and gallery.thumbs_prepend_site_url  set to yes.

I noticed that in the file that I am loading the images in "files", when doing the single image load is only loading one image in it and I mean only one. So if you do singles there is only one image, not sure what thatmeans yet, but if you do the bach it loads all the images in the file.

My hunch, which I do not have time to look for right now, is that it is going to be a permissions issue or the code for single and multiple is not writing the name of the path and file correclty. So if anyone wants to start tracking this down that would be great. Who knows a collaberation we may resolve the issue.

Thank you

**Comment by wholein1** [comment]
Another update.

I deleted Gallery 1.5 DB tables, uninstalled the 1. 5 Gallery package completely, by forcing the uninstall. Then went and added 1.4 zip file to core/packages. Once zip file loaded, I went to the package manager and loaded 1.4. I left configurations as is and uploaded images. The end result is everything worked in 1.4 Gallery, 

So I am thinking it is int he code. I am going to look it over some time over the next few weeks.

**Comment by philkirkman** [comment]
marvellous, my entire business model depends on revo and a working gallery :)

**Comment by philkirkman** [comment]
many thanks janice and people

**Comment by chunkyRice** [comment]
@wholein1 I posted a reply in thread #197, concerning the same issue. It seems that when uploading single files, gallery 1.5.0 rc1 doesn't replace the filenames with consecutive numbers, but with the number of the gallery. Since that is always the same, images are overwritten with each upload.
