### ISSUE TITLE
Pagination inside Gallery CMP

### ISSUE THREAD

**Issue by oksushi** [splittingred/Gallery#193]
Using galleries with more than 8 thumbnails, we’ve encountered the following issue. The total number of images is reported correctly, however there is no way to progress past the first page of thumbs.

See the following example:

https://skitch.com/calwilson/8uthd/gallery-cmp-issue

With this particular one, the initial page load shows 7 thumbs. After clicking the 'refresh' icon beneath, I see 8 thumbs. The Forwards and Previous buttons are never clickable, neither does the 'Page 1 of 1' change.

**Comment by niedarek** [comment]
Have you find a solution? I have the same issue.

**Comment by oksushi** [comment]
No, not yet.

**Comment by niedarek** [comment]
I've installed new version 1.5.0 pl (previous 1.5.0. rc) and it's now working corectly.

**Comment by sonicpunk** [comment]
My client just came to me with this issue as of today.   We are running Revo 2.2.2 and Gallery 1.5.1.

**Comment by chrisderover** [comment]
Running Revo 2.2.2-pl with Gallery 1.5.1 and I have the same issue. 
I my case it has something to do with adding tags to images.
When I add tags to the first 4 images everything is fine, but when I add tags to any next item it will hide all the other images except the 5 items I've tagged...

**Comment by frauplote** [comment]
Same issue here. Running Revo 2.2.4 with Gallery 1.5.2.

**Comment by gadgetto** [comment]
Same problem here: adding tags in upload dialog causes the problem!
Revo 2.2.4-pl and Gallery 1.5.2
