### ISSUE TITLE
gallery 1.5.0. "Upload Item" don't work properly.

### ISSUE THREAD

**Issue by vbf** [splittingred/Gallery#197]
Hi

I have new installation of MODx 2.2.1 and Upgrades from 2.0.x to 2.2.1 

"Upload Item" always duplicate first item only in new installation of  MODx 2.2.1

**Comment by chunkyRice** [comment]
When uploading a file it seems the gallery id is used as the filename, instead of the gallery item id. The problem occurred after I upgraded from MODX 2.1.4 to 2.2.1, upgrading Gallery in the process from 1.4.0 rc1 to 1.5.0 rc1.

I see this issue was already reported as ticket #188
