### ISSUE TITLE
Manager Album Sort

### ISSUE THREAD

**Issue by oksushi** [splittingred/Gallery#198]
In the CMP for Gallery, one is able to drag & drop to change the order of the albums, however this order is lost if Refresh is pressed, or the page is reloaded.

The MODX standard functionality (seen in the resource tree) is that drag and drop will modify order (in that case, menuindex).

I notice that the database has a 'rank' field, and the albums can be sorted by this field, however there doesn’t seem to be a way to manipulate this value?

**Comment by nickff** [comment]
When you drag an album, chrome dev tools spits out this error:

"Uncaught SyntaxError: Unexpected token < in ext-all.js on line 7"

**Comment by Mikaro** [comment]
firebug doesn't show me errors.

in error log:
(ERROR @ .../.../core/components/gallery/processors/mgr/album/sort.class.php : 19) PHP warning: urldecode() expects parameter 1 to be string, array given

Gallery 1.5.0 rc1

**Comment by nickff** [comment]
Sorry, meant to say "chrome dev tools".

**Comment by Mikaro** [comment]
I removed urldecode() on line 19 of core/components/gallery/processors/mgr/album/sort.class.php
$this->data = is_array($data) ? $data : $this->modx->fromJSON($data);

**Comment by nickff** [comment]
Worked! Thanks so much @Mikaro.

**Comment by brlanier** [comment]
You can try moving the urlencode() to wrap the $data array directly to respect the original intention.
From:
$this->data = is_array($data) ? $data : urldecode($this->modx->fromJSON($data));
To: 
$this->data = is_array($data) ? $data : $this->modx->fromJSON(urldecode($data));

I have confirmed that this works for me and preserves the rank and parent relationships in the database.

**Comment by Mikaro** [comment]
right thanks brlanier

**Comment by Citric** [comment]
Adding this fix to v1.5.2 under Revo 2.2.5-pl is no longer working for us.

The drag and drop sorting seems to be defaulting to '4' and can only be overridden in PHPMyAdmin.

**Comment by dezzer** [comment]
Hi, 
Citric can you tell me where exactly is in sql databases value=4 of default sorting . I have no idea how find it.

**Comment by Citric** [comment]
Hi

@dezzer Within PHPMyAdmin, click on the table 'modx_gallery_album_items' and the image results will be shown. The last column is 'rank' and that's where you can override the sort number.

**Comment by dezzer** [comment]
i have strange behavior in this table , i get album number 2 with 8 images, and three of this image have rank 7 , and this was my problem why i cant sort image in manager(drag and drop)

thanks .

**Comment by Citric** [comment]
That's the same issue we had and this was the only way to change it as the other fixes didn't work.

**Comment by dezzer** [comment]
good idea will be add posibility to change rank in manager on image edit .

@Citric  thanks for the quick reply.
