### ISSUE TITLE
1.5.0 rc1 Drag and drop + rank problem

### ISSUE THREAD

**Issue by Citric** [splittingred/Gallery#202]
Spec: Revo 2.2.2, OS X, Firefox, Chrome, Safari + Opera.

When dragging/dropping gallery items into a preferred order, sometimes the order is saved and other times it does its own thing, which is hard to control.

This is obviously affecting the item's rank: within PHpMyAdmin some items have been allocated the same rank position and the only workaround we've found is to manually sort the rank within here, which kind of defeats the purpose of a drag/drop interface, especially for client sites!

Additionally, the pagination sometimes show 20 items and then 24. We've overridden the $limit within the snippet's PHP to increase the number of items visible at a view and it is ignored, even after clearing the cache.

Is this an ExtJS quirk or the snippet?

**Comment by danyaPostfactum** [comment]
It would be interesting to you: https://github.com/splittingred/Gallery/pull/205

**Comment by Citric** [comment]
Will check it out, thanks.

**Comment by Citric** [comment]
v1.5.0-pl seems to have fixed this issue
