### ISSUE TITLE
Thumbnail position

### ISSUE THREAD

**Issue by Showa** [splittingred/Gallery#215]
I already asked this in the MODX forum but got no answer, so I would like to have a go here.

In gallery viewing an album the thumbnails are positioned vertically. I would like to position them in a row, where do I have to chance this and what do I have to change. I am using Revo 2.2.2 and Gallery 1.5.0. 

Now:

Thumbnail1
Thumbnail2
Thumbnail3
Thumbnail4
etc.

Preferred:
Thumbnail1 Thumbnail2 Thumbnail3 Thumbnail4 
Thumbnail4 etc.

Ad.

**Comment by nicboyde** [comment]
Probably not a MODx or Gallery issue.

Use CSS. IMG float:left should do it.

**Comment by Showa** [comment]
I have got this in style.css

/\* Gallery */
.gal-item{
    float: left;
    margin: 10px 10px 10px 0px;
    text-align: center;
}

.gal-item a{
    display: block;
}

.gal-item img{
    float: left;
    border: solid 4px #CCC;
    width: 227px;
}

.gal-item img:hover{
    border: solid 4px #666;
}

Makes no difference.

**Comment by nicboyde** [comment]
You are looking at the wrong place  in the stylesheet. This isn't the place to discuss CSS matters. PM me via the MODx forum - username nicboyde. Suggest close this issue here.

**Comment by Showa** [comment]
Issue closed
