### ISSUE TITLE
Link to thumbnail gets a double replacement

### ISSUE THREAD

**Issue by sewid** [splittingred/Gallery#23]
Hi,

I've just installed 0.1.2 rc2 and discovered, that links to the thumbnails gets a double replacement. Instead of http://example.com/something?another&amp;anything=1 it shows http://example.com/something?another&amp;amp;anything=1

I had to modify the galitem.class.php like this to get it correct:
            case 'thumbnail':
                $value = $this->getPhpThumbUrl();
                if (empty($format)) $format = array();
                $format['src']= MODX_URL_SCHEME.MODX_HTTP_HOST.$this->xpdo->getOption('gallery.files_url').$this->get('filename');
                $url = $value.'?'.http_build_query($format);
                //$value = str_replace('&','&amp;',$url); // This has to be removed.
                $value = $url;
                break;

Best regards,
sewid

**Comment by splittingred** [comment]
Fixed in http://github.com/splittingred/Gallery/commit/0ace31fb16e313c5ed14ad15c1af7e9c8ce61fab
