### ISSUE TITLE
galItemThumb Chunk generates invalid html

### ISSUE THREAD

**Issue by sewid** [splittingred/Gallery#24]
Hi,

the linebreaks in galItemThumb have to be removed, to get valid html.

It has to look like this:
    <div class="[[+cls]]">
        <a href="[[+linkToImage:if=`[[+linkToImage]]`:is=`1`:then=`[[+image_absolute]]`:else=`[[~[[*id]]?
                &[[+imageGetParam]]=`[[+id]]`
                &[[+albumRequestVar]]=`[[+album]]`
                &[[+tagRequestVar]]=`[[+tag]]` ]]`]]">

```
        <img class="[[+imgCls]]" src="[[+thumbnail]]" alt="[[+name]]" />
    </a>
</div>
```

Best regards,
sewid

**Comment by splittingred** [comment]
Fixed in http://github.com/splittingred/Gallery/commit/0ace31fb16e313c5ed14ad15c1af7e9c8ce61fab
