### ISSUE TITLE
phpthumb cache not working

### ISSUE THREAD

**Issue by sewid** [splittingred/Gallery#25]
Hi,

in the current version (1.0.1 rc1), the phpthumb cache is not working for me. Neither on a windows dev environment, nor on my mac dev environment. 

But: gallery is a great plugin! :-)

Best regards,
sewid

**Comment by snlr** [comment]
Same here on Ubuntu 10.4. Images are not shown in frontend + backend.

**Comment by sewid** [comment]
Images are shown in front- and backend, but not cached - so this might be a different problem?

**Comment by jonrawlins** [comment]
I have the same trouble, therefore it takes ages to load the page each time.

**Comment by splittingred** [comment]
Fixed in 1.0.1-rc2
