### ISSUE TITLE
&sort=`rand` Random first time only

### ISSUE THREAD

**Issue by moniarde** [splittingred/Gallery#258]
I have a really basic call to Gallery on one of my template chunks: [[!Gallery ? &album=`4` &thumbTpl=`galRandom` &sort=`rand` &imageHeight=`100px`]]. All I want is one image from an album, but I want a different image on every page load. I am getting a random image once I make a change that alters the cache, but unless I alter the something (move an image in the gallery, add a parameter to the call, something small), the same image that was last called is displayed on every page and on every page refresh.

I've looked at all of the images at once - they are in a random order, but that order stays the same until I change something. I have my Gallery call uncached - is there something that is caching the output of the call to reuse it later?

**Comment by achterbahn** [comment]
I had the same problem. @alexgloom: did you mean issue 259? This is the problem of GalleryAlbum-Snippet. 

I solved the problem with shuffling the array that comes from the function getList in galitem.class.php.

In  
`if ($modx->getCacheManager() && $cache = $modx->cacheManager->get($cacheKey)) {}` I added the following:

`if (in_array(strtolower($sort),array('random','rand()','rand'))) {
shuffle($items);
}`
and moved the script property 
`$sort = $modx->getOption('sort',$scriptProperties,'rank');` up to the top of the function.

Now it randomizes the array that is pulled from the cache.

**Comment by legkomedia** [comment]
I have the same problem and I found a simple solution.
in galitem.class.php at ~ line 247
change this line
`if ($modx->getCacheManager() && $cache = $modx->cacheManager->get($cacheKey)) {`
to these two 
`$sort = $modx->getOption('sort',$scriptProperties,'rank');
if ($modx->getCacheManager() && $sort != 'rand' && $cache = $modx->cacheManager->get($cacheKey)) {`

This solution will allow skip the cache

**Comment by jpdevries** [comment]
@legkomedia any chance you could submit a PR for this over at modxcms/Gallery?

**Comment by legkomedia** [comment]
@jpdevries I'm sorry, I'm new to github and do not know how to do it.
If you see a need for this, you can do it yourself?

**Comment by jpdevries** [comment]
no problem @legkomedia. I'm comparing your method with @achterbahn's method. It looks likes @achterbahn way allows for cacheing not to be entirely by passed. Any chance you could submit a PR @achterbahn?

**Comment by jpdevries** [comment]
@achterbahn Thanks! Got this merged over at the modxcms develop branch
https://github.com/modxcms/Gallery/commit/949570a5e548e4d0d72e30f0c26041858a0c9bf5

**Comment by jimboroberts** [comment]
I'm still having issues with images not rotating. My gallery holds quite a few images, but after the first call [[!Gallery? &album=`1` &thumbTpl=`galItemThumbGallery` &sort=`random` &limit=`25`]] there is no change unless site cache is emptied. This is even after updating to modxcms@949570a

**Comment by jimboroberts** [comment]
Has anyone else had this same issue?
