### ISSUE TITLE
File Tree Not Showing IN Gallery Browser

### ISSUE THREAD

**Issue by Northie** [splittingred/Gallery#27]
I think the title says it all.

I have installed Gallery v1.0.1 rc1 and created a TV as directed in the documentation

I can see the gallery plugin on the resources that have been assigned the TV

When I go into the TV and click "Choose an Image" I get a window very similar to the modx file browser but the left column is empty. I expect to see the file tree and some controls (like an upload button).

I am therefore unable to upload or choose any images to put in a gallery!

**Comment by adamwintle** [comment]
Yeah, I'm also getting this issue - anybody worked out what's causing it?

**Comment by Northie** [comment]
I don't think that this is an issue - the fact is that the gallery plugin just isn't very intuitive to use. You can view the file tree when you add files to the gallery through the main gallery menu (under components). The images you choose there then become available in the pop up box seen when in the template variable

**Comment by splittingred** [comment]
This isn't a bug; the tree in the Gallery TV is for Albums, not files. You have to create an Album first.
