### ISSUE TITLE
Permissions issue when uploading items to a gallery

### ISSUE THREAD

**Issue by simonp98** [splittingred/Gallery#279]
I have an issue that I am struggling to solve. This may not be a bug with Gallery itself, but I am all out of ideas so am turning here for help.

I am developing locally on OSX Lion (10.7.5) using Zend Server CE with PHP 5.3.9 with MODx 2.2.13-pl and Gallery 1.6.1

In order for Gallery to create a directory for a gallery I need to set permissions on my site root directory to 777. If I don't then not directory is created in assets/gallery with the following error.

```
(ERROR @ /assets/components/gallery/connector.php) [Gallery] Could not create directory (possibly already exists?): assets/gallery/3/
```

The directory doesn't exist. Its just that the call to createContainer() from galalbum.class.php is returning false as it tests the site root directory for read/write permissions rather than the assets or gallery directory. My thoughts are that I have an erroneous setting somewhere, but cannot find it. I am using the default system settings for Gallery.

Any help would be appreciated. Thanks in advance

**Comment by jpdevries** [comment]
Hm, This sounds like an issue related to your environment. Whatever user php is running as needs read/write to assets/*.

## 

JP DeVries
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by simonp98** [comment]
Thanks for the quick response. I'm a bit naive where detailed permissions are involved. PHP runs as daemon on my machine. assets is set to 777, is owned by me (as are most directories including the root of the dev site). I did change the ownership of the root directory and assets to daemon and it made no difference?

**Comment by jpdevries** [comment]
If MODX is running correctly, I'd take a look what the permissions are of the core/cache files it creates. 777 shouldn't hurt you locally, but certainty don't want to have to do that in an actual environment. 
We use MODX Cloud to help tests things like this and try and reproduce issues. let me know if you'd like access to a Manager to try and reproduce this issue.

**Comment by simonp98** [comment]
Yes your right. I've just compared the cache premissions and changed owner/group on the root to daemon/staff, set permissions to 755 and everything appears to work. Thank you very much for your help.

**Comment by lithiumlab** [comment]
I'm getting this warning in the console  every time a file gets uploaded.

` ` `
[Gallery] Could not create directory (possibly already exists?): assets/gallery/5/
` ` ` 

The files are being uploaded correctly, folder created and thumbs generated.
But this error keeps coming.

I'm using windows server 2008 r2
How do i make sure what is the user being used by the php process?
