### ISSUE TITLE
Manager login/logout trouble when "anonymous_sessions" = 0 in Modx 2.5.0-pl

### ISSUE THREAD

**Issue by ilyatut** [splittingred/Gallery#294]
Hello!

After updating from my previous Modx 2.4.4 to Modx 2.5, setting the "anonymous_sessions" option to "0" and logging out, I was unable to log in back to the Manager. Newly created super-admin users were unable to log in to the Manager too.

I submitted the issue here: https://github.com/modxcms/revolution/issues/12983 and after some research finnaly found that the problem disappears when I'm uninstalling the Gallery extra.
 I've done the next two things:
1) I uninstalled Gallery on my working project and the mentioned issue disappeared.
2) I installed Gallery on a brand new Modx 2.5.0-pl, turned "anonymous_sessions" off, logged out and got exactly the same trouble trying to log in!

So, it looks like there is something in the Gallery extra, somehow connected to sessions and causing this login/logout trouble. Could you please take a look at what it might be?

**Comment by pixelchutes** [comment]
@ilyatut Gallery issues are currently maintained here: https://github.com/modxcms/Gallery/issues

**Comment by ilyatut** [comment]
@pixelchutes Oк, thanks! Will try it again:)
