### ISSUE TITLE
Feature-request: Mass-upload (.zip/.rar/.tar.gz??)

### ISSUE THREAD

**Issue by StevenLangbroek** [splittingred/Gallery#3]
Some of my clients have _alot_ of images to upload into galleries. In the long run being able to upload a ZIP-file or something like that would probably be the best option I think (as it doesn't require any explanation). Is this a possibility that could be researched for future use?

**Comment by mkschell** [comment]
Perhaps a separate 3PC could provide this functionality, not only to Gallery but any other component that will use files. I also wonder if a 3PC could register custom functionality into something like the context menu of the File Manager.

**Comment by splittingred** [comment]
Batch upload is in latest version

**Comment by StevenLangbroek** [comment]
Hi splitting,

I think the implementation is pretty sweet, but FTP might be a bit too complex/dangerous for some clients. Might it be possible to implement a multi-upload script in the future? Think about it :).

Best!

Steven

**Comment by djemmers** [comment]
I agree with Steven.
