### ISSUE TITLE
get random image from album

### ISSUE THREAD

**Issue by ghost** [splittingred/Gallery#33]
It will be nice to grab a random image (or thumb) from an album (or all albums).

**Comment by jobatkin** [comment]
This could also be useful when listing all albums - a random image from within the album would be nicer to display than just the name and description.

**Comment by Hypercubed** [comment]
In the gallery snippet I replaced the line 

```
$c->sortby($sortAlias.'.'.$sort,$dir);
```

with

```
if (strcasecmp($sort,'rand')==0) {
    $c->sortby('RAND()',$dir);
} else {
    $c->sortby($sortAlias.'.'.$sort,$dir);
}
```

then I can get a random image with

```
[[!Gallery? &sort=`RAND` &limit=`1`]]
```
