### ISSUE TITLE
[IMPR] TV Output generate only PNG files

### ISSUE THREAD

**Issue by mIDOnf** [splittingred/Gallery#35]
When we use the TV Output it only generate PNGs instead of showing the output in the same format than the original or letting us to choose what format to output using properties. For example, we have some JPG files wich size is 13Kb but are shown in PNG with a size of 73Kb!!!

The "problem" is in line 66: 'f' => 'png',

of 

elements/tv/output/galleryitem.php

**Comment by mIDOnf** [comment]
Same for quality, for example:
            'q' => '95'

**Comment by splittingred** [comment]
Just set in the Other options:

f=jpg&q=95

Done.
