### ISSUE TITLE
Error message by Firebug GAL is not defined

### ISSUE THREAD

**Issue by stratboy** [splittingred/Gallery#36]
Hi! If I click on Components/Gallery, nothing appears, and Firebug say me this:

'GAL is not defined'
manager?a=74 (row 25)

I'm using Revo 2.0.3-pl

**Comment by stratboy** [comment]
Note: my Revo is an upgrade on an existing installation of the latest Evo. Should I maybe use a fresh installation of Revo instead? Or, maybe, should I use Evo for now?

**Comment by splittingred** [comment]
Can't reproduce; must be an environment issue with your install.

**Comment by wassolls** [comment]
had the same problem. Changing permissions of
 .../assets/components/gallery 
and all files and dirs in this directory to 755 allowed me at least see a create album button. 
But when I want to save a new album, I get a short saving message and then I'm back to the create album popup, with no Album created.

firebug shows the following errormessages:
my.url/assets/components/gallery/connector.php?HTTP_MODAUTH=...&action=mgr%2Falbum%2Fcreate&description=fgh&name=fgh
500 Internal Server Error
[replaced the part after HTTP_MODAUTH=with...]

A is undefined
MODx(A=undefined, B=Object { url="/assets/components/gallery/connector.php"...

so I guess permissions to some file or folder are still wrong? any clues?
