### ISSUE TITLE
MODx Revolution 2.0.4pl2 update creates conflict with Gallery

### ISSUE THREAD

**Issue by sonicpunk** [splittingred/Gallery#44]
I had a website on Revo 2.0.0 working correctly with the Gallery tool.  As I then began to upgrade the 2.0.3, then 2.0.4, the file manager stopped working correctly.  After much discussion on the modx forum, it came out that MODx was not the issue, but the Gallery tool.  For some reason, the folders that I stored images in that I used for my batch loading into the Gallery could no longer be opened by the file manager.  I would get the error ""Please specify a valid directory"" and it would cause the tree structure to close.  As this is a problem with a live site, and I have an unhappy client, I would appreciate it if this could be looked at.  Thanks.

**Comment by silentworks** [comment]
Roll back to 2.0.3 and always do updates on a development machine before pushing it to a live server. Until a fix is ready you will have to stick with 2.0.3 for now.

**Comment by sonicpunk** [comment]
How does one rollback to a previous version? According to my memory, the same bug existed in 2.0.3, but am not sure.

**Comment by sonicpunk** [comment]
Accidentally closed the issue..how do I reopen it?

**Comment by eerne** [comment]
Could you post a link to the forum thread?
and are you working in the web context or custom context?

not sure how to reopen the issue.

**Comment by sonicpunk** [comment]
I can't get a link from the URL.  The thread is located here:
MODx Community Forums / Support / Release Support / Revolution 2.0 (Moderators: rthrash, OpenGeek, splittingred, smashingred) / File Manager showing this error "Please specify a valid directory"

**Comment by eerne** [comment]
hi i think you have to re-issue this issue otherwise it gets lost

**Comment by sonicpunk** [comment]
Thanks for the post.  It turns out however that I can reproduce the error without the gallery tool being installed....which makes my situation worse....:(

**Comment by eerne** [comment]
ok then i leave the issue closed here. and write a new one on http://bugs.modx.com/ with detailed step by step instruction how to reproduce the problem and what environment you use.
