### ISSUE TITLE
[FR] Watermarking

### ISSUE THREAD

**Issue by jobatkin** [splittingred/Gallery#46]
I know you mentioned that this was already being considered as a future feature, but thought I'd raise it here as well as it's something I would find really useful. I know phpThumb has watermarking features included in it so will possibly try going down that road but would love for it all to be included in Gallery =)

**Comment by splittingred** [comment]
Fixed; now can pass any phpThumb options through &thumbProperties and &imageProperties on most snippets: 
https://github.com/splittingred/Gallery/commit/49261f7a9a669c37d9f337c02005e66474ff28ee
