### ISSUE TITLE
[FR] hide name/random thumbnail

### ISSUE THREAD

**Issue by christophlutz** [splittingred/Gallery#48]
I have two requests/suggestions
- being able to add a parameter to the snippet to not display the image name - this would allow not to display names where they are only the name of the file and where no name for the image is needed/desired but a load of file names look a bit rubbish
- being able to display an album with an individual (random) thumbnail from the gallery to allow users to visit the full gallery by clicking onto the thumbnail

Otherwise, good work, thank you!!

**Comment by splittingred** [comment]
1. Do you mean for the GalleryAlbums snippet? Which snippet are you referring to? You can always override the tpls for each snippet.
2. can already be done: [[!GalleryAlbums? &albumCoverSort=`random`]]
