### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by avoronkin** [splittingred/Gallery#5]
Hi!
In assets/components/gallery/js/mgr/widgets/home.panel.js on line 18 hardcoded  title: 'Albums'.

Russian translation here http://dl.dropbox.com/u/3483977/russian.translation.gallery.011pl.zip
In translation i used 'gallery.albums' for hardcoded Albums.

**Comment by splittingred** [comment]
Done in Gallery 0.1.2-rc2
