### ISSUE TITLE
Images not displaying in Gallery Manager or on site

### ISSUE THREAD

**Issue by vcc033** [splittingred/Gallery#53]
I have got the same problem as in [[http://modxcms.com/forums/index.php/topic,55472.0.html]]
In the resource browser of modx thumbs are working normaly.

errorlog:
22:05:03] (ERROR /~atlas/assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 557
[2010-11-26 22:05:08](ERROR /~atlas/assets/components/gallery/connector.php) [Gallery] phpThumb was unable to generate a thumbnail for: /home/atlas/domains/atlas-afbouw.nl/public_html/core/cache/phpthumb/phpThumb_cache_85.92.147.71_src49c4c2e9069b48ecbdc4d8850fb6d3a0_parc0577b6af55be2f1fe29bd4dad092394_dat0.jpeg
[2010-11-26 22:05:08](ERROR @ /~atlas/assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 557

output of the snippet:

<img class="" src="/~atlas/assets/components/gallery/connector.php?action=web/phpthumb&w=100&h=100&zc=1&far=1&src=%2F%7Eatlas%2Fassets%2Fcomponents%2Fgallery%2Ffiles%2F2010%2F11%2Fatlas.bmp" alt="atlas log" />

Environment: Revolution 2.0.4-pl2, FF3.6.12, IE8, gallery 1.0.1 rc2, GD enabled and ImageMagick is in: /usr/bin

**Comment by vcc033** [comment]
I  upgraded the installation and problem is solved.

**Comment by krisj** [comment]
what do you mean by "upgraded the installation" I am having trouble with Revo 2.0.7 pl server environment is all good.

**Comment by vcc033** [comment]
I have upgraded the installation to 2.0.5 and the problem was gone. With Revo 2.0.7 pl  I experienced the same problem again. But I find out that the problem was the setting_phpthumb_allow_src_above_docroot_desc parameter. I must be set on YES.

**Comment by krisj** [comment]
tried that setting, now I am getting thumbnails in resource content, but not in gallery. Error messages are the same. Going to see what php/apache logs reveal...

**Comment by vcc033** [comment]
Krisj,

Change in system settings: Prepend Site URL to Thumbs in the gallery section to YES.

**Comment by krisj** [comment]
Thanks for the suggestion, still failing. I should probably mention though thtat I am running Nginx in fron of Apache. THe rest of the system works perfectly fine, just the gallery screwing up with thumbs.

I am noticing that Apache is dying with:
[Sun Jan 30 23:11:27 2011] [notice] child pid 19074 exit signal Segmentation fault (11)

gonn get the coredump i guess..

**Comment by krisj** [comment]
OK, I am getting somewhere.
Turns out eAccelerator was causing segfaults when working behind scenes with FastCGI and Nginx as reverse proxy in front of Apache. I have removed it and it seems to be working great so far. Investigating as in how to get it working with it installed though...

**Comment by krisj** [comment]
I would also like to add that with Revo 2.0.7 pl and eAccelerator uninstalled the default settings work fine too.

Funnily enough they mention that eAccelerator should be switched off during installation in the MODx wiki site. Looks like it also does not play nice with the Gallery. At least the versions of PHP/Apache/eAccelerator/FastCGI i've been using...
