### ISSUE TITLE
off-server thumbnailing is not allowed

### ISSUE THREAD

**Issue by ashiazed** [splittingred/Gallery#59]
When adding an image to a document through the custom TV an error:
off-server thumbnailing is not allowed.

**Comment by splittingred** [comment]
Fixed in Revo 2.0.5, and in an upcoming Gallery bugpatch.

**Comment by ashiazed** [comment]
Note: currently running 2.0.5-pl already. Will wait for gallery patch.

**Comment by splittingred** [comment]
It's been released, 1.0.1-pl.

**Comment by ashiazed** [comment]
Just testing the new gallery. Noticed that you can't choose an image. Selecting the album on the left hand side takes you to the gallery manager instead of showing items to choose.
