### ISSUE TITLE
Invalid URL formatting

### ISSUE THREAD

**Issue by Nacnud** [splittingred/Gallery#6]
Sean - thanks for fixing the '&' -> '&amp;' problem
Unfortunately the issue I flagged as a comment on that ticket is related, but is a different problem and still needs fixing.

In summary - I'm getting URL's like the following
http://axe/modx-2.0.0-rc-1/index.php?id=19?galAlbum=3
You can see the second '?' which should be a '&' this is an incorrectly formatted URL and results the page parameters being ignored.
The following text is a copy of my comment on the original ticket (#2) - it describes what still needs to be done to get Gallery working in a default MODx installation.

It can be worked around by editing pre-defined chunks galAlbumRowTpl and galItemThumb; and creating two custom chunks galItemAlbum and galItemTag. The purpose of these chunks is to swap '?' for '&'. I've added details into the Gallery 0.1.0 rc2 Support thread.
The '&' is needed if MODx is used in default configuration and '?' is needed is Search Engine Friendly URLs are being generated.
The fix is probably to create the URL's in the snippet; doing it in the chunk will be fairly verbose and prone to user error.

**Comment by Nacnud** [comment]
Here's a link to the 0.1.0 RC2 forum with the details posted in it

**Comment by Nacnud** [comment]
http://modxcms.com/forums/index.php?topic=50118
DOH!

**Comment by splittingred** [comment]
Fixed in 0.1.2-rc2
