### ISSUE TITLE
Add abilty to assign image to multiple galleries or move to diff gallery

### ISSUE THREAD

**Issue by onepack** [splittingred/Gallery#63]
Hi Shaun,

It would be a great feature if there would be an ability to assign an image to a different available gallery in the gallery image detail page. Or to more galleries so that an image can be in more than 1 gallery in the same time. Or a way to drag an image from Gallery A to Gallery B.

To illustrate this. I have a customer who has paintings on the website. Some are private and some are for sale. There are some paintings the owner decided not to sell and some that were private will come for sale now. The only way now is to remove the image from Gallery A and import again into gallery B. All the Image Descriptions etc will be lost by doing so and will have to be updated again. The ability to assign a picture to a different available gallery in the Image Detail page would solve this.

Thanks for your patience with my poor English.

OnePack

**Comment by drwagner13** [comment]
I second this. An essential feature, much needed

**Comment by yurkobb** [comment]
Agree

**Comment by onepack** [comment]
4 Years later. Closed!
Please create a new case if someone still thinks this is valid.
