### ISSUE TITLE
[FR] Unique filenames and folders for albums

### ISSUE THREAD

**Issue by Neon4eg** [splittingred/Gallery#64]
All uploaded files are stored in one folder with same names! 
I was uploading 23 packs of files with similar names like 1.jpg ... 32.jpg and was very surprised when saw that new files with same names where ignored! Are you kidding? It`s absolutely unusable!
So each album should have its own folder and all files should be renamed by unique name.

**Comment by splittingred** [comment]
Done: https://github.com/splittingred/Gallery/commit/8e8e53f9534e74d590ef714d5622e774bc2aac53

**Comment by GuidoGallenkamp** [comment]
I am so glad this is fixed :)
