### ISSUE TITLE
Instantiated a derived class galItem that is not a subclass of the requested class galAlbumItem

### ISSUE THREAD

**Issue by Cipa** [splittingred/Gallery#66]
Hi, I get this error every time I click an album item

[2011-02-20 21:41:06](ERROR @ /new/index.php) Instantiated a derived class galItem that is not a subclass of the requested class galAlbumItem

I wrote a tutorial here: http://modxrules.com/articles/modx-revolution-gallery-with-colorbox-and-jquery-asynchronous-image-loader-jail

I don't think the error is related to the way I use Gallery but I might be wrong. This looks more like a php OOP error

Thanks

**Comment by lithiumlab** [comment]
Some of us also have experienced this.
See: http://modxcms.com/forums/index.php/topic,58810.msg348368.html#msg348368

**Comment by martinf55** [comment]
I think there is a small bug in the GalleryAlbums snippet at line 86 (in 1.0.2rc2).
The final line of this sequence:

```
$c = $modx->newQuery('galItem');
$c->innerJoin('galAlbumItem','AlbumItems');
$c->where(array(
    'AlbumItems.album' => $album->get('id'),
));
$c->sortby($albumCoverSort,$albumCoverSortDir);
$c->limit(1);
$coverItem = $modx->getObject('galAlbumItem',$c);
```

should read:
    $coverItem = $modx->getObject('galItem',$c);

This ensures the getObject is being called for the primary class in the query. For some reason this error only showed up when I altered the caching spec on a top-level TV call (to non-caching), so I suspect under some circumstances xPDO manages to work out the correct class name.

**Comment by splittingred** [comment]
Fixed: https://github.com/splittingred/Gallery/commit/46a6908519a758c87574e10d8f3ab83e683401fe

**Comment by lithiumlab** [comment]
Thanks a lot!
