### ISSUE TITLE
Galleriffic pagination - wrong lexicon key

### ISSUE THREAD

**Issue by nd2s** [splittingred/Gallery#67]
When using Gallerific and pagination, there is only "next" shown - no "previous".

This is because in
core/components/gallery/model/gallery/plugins/galleriffic.class.php
on line 50 "$this->modx->lexicon('gallery.next')" is used twice, it should be replaced with
"$this->modx->lexicon('gallery.prev')".

**Comment by splittingred** [comment]
[#67] Fix prev lexicon placeholder in Galleriffic plugin; closed by 62c12c9bed9e562dfa39f34b30a9838b0987b9e9
