### ISSUE TITLE
Images don't up in gallery TV

### ISSUE THREAD

**Issue by pepebe** [splittingred/Gallery#73]
Images are not displayed inside gallery TV because phpthumbof doesn't seem to accept a absolute URL as src variable. This might be related to the "gallery.thumbs_prepend_site_url" system setting and a MODx bug that sets "No" to empty instead of "0" or "false".

For more information have a look at : http://modxcms.com/forums/index.php/topic,62137.0.html

**Comment by splittingred** [comment]
[#73] Fix issue with absoluteImage galItem issue and gallery.thumbs_prepend_site_url setting; closed by 178f9bd3d3d2f4c740e5cc035202837c548f6506
