### ISSUE TITLE
Tags not updating correctly

### ISSUE THREAD

**Issue by AugmentBLU** [splittingred/Gallery#74]
After adding a tag to an image after upload, click the image and add a tag, save.  Go back to the image again and delete the tag then add a new tag and save.  It retains the first tag, adds the next and if you add another there after it keeps tacking them on.

Hope that is clear.

gallery 1.0.2 rc2
MODx Rev 2.0.8

**Comment by splittingred** [comment]
Update to 1.1.0; I cant replicate this in that version.
