### ISSUE TITLE
MODx error log gets filled with these while browsing

### ISSUE THREAD

**Issue by krisj** [splittingred/Gallery#75]
Every time I browse the gallery in the frontend the MODx error log gets filled with these:

OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3652
[2011-03-15 02:47:43](ERROR @ /assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

thumbs and images are showing OK though...

**Comment by lithiumlab** [comment]
I'm having the same issue too.
Please see: 
http://modxcms.com/forums/index.php/topic,60402.msg353411.html#msg353411

**Comment by splittingred** [comment]
Do you get any errors in core/cache/logs/error.log?

**Comment by lithiumlab** [comment]
Cleaned the error log and did a test uploading a couple of files right now and yes, im getting the errors in core/cache/logs/error.log:

 [2011-03-16 10:53:44](ERROR @ /assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3652
[2011-03-16 10:54:07](ERROR @ /assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3652

**Comment by daitj** [comment]
i am also facing the same problem , all permission are confirmed, gd is also on in phpinfo, i moved the website from one server to another and start facing such problem. the only difference in two servers are the php version 5.2.12 and 5.2.14

OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3652
[2011-03-22 11:25:24](ERROR @ /assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

**Comment by lithiumlab** [comment]
I'm using PHP 5.2.13

**Comment by daitj** [comment]
@lithumlab did you move files to another server or something like that before this happened?

**Comment by lithiumlab** [comment]
no, it's a clean install just to try this.

**Comment by daitj** [comment]
@lithumlab have you found any workaround , coz it is really bugging me , i have transparent pngs in the gallery and it give a really creepy thumbnail with black background, and also doesn't give the thumbnail with passed height and width.

for me it only happens for pngs not for jpgs
and also for jpgs everything works fine
i tried to change 'w' and 'h' in the image link
assets/components/gallery/connector.php?action=web/phpthumb&w=800&h=500
for jpgs it works fine but for png if i change those image is not displayed at all

info: In phpinfo under gd 
PNG is ENABLED

**Comment by lithiumlab** [comment]
I've only used Gallery with .jpg files, they work good, but still the error log is getting filled with the errors.

**Comment by lithiumlab** [comment]
This error is still reproducible in my environment even with 2.1.0-rc1, fresh install.
Why is this issue tagged as 'Not reproducible'? Is there anything else i can do to check this? Any hints about what can i do to give more detail about the error?

**Comment by daitj** [comment]
my issue was solved , i had to pass bg=#FFF to make bg of a png file white(for some reason in new server black was default)
but still i m getting this error in my error log.
I also tried a fresh install with 2.1.0-rc1, still i can see the error.
as lithiumlab said why this is tagged as 'Not reproducible'?

**Comment by ghost** [comment]
I have the same error message: 
OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3652
[2011-04-09 03:18:54](ERROR @ /nefrouros/assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

My gallery all in .jpgs, and work fine but this error spam my log file, every day betwen 40k to 100k :(

I have the last gallery version and the error happen also with previous version

**Comment by Mark-H** [comment]
I've had this before, and some of the paths seemed to be off. 

Go to the System Settings, find phpthumb in the Area dropdown and make sure the paths are correct there.
