### ISSUE TITLE
ZIP Upload does not show images after upload

### ISSUE THREAD

**Issue by roele** [splittingred/Gallery#76]
After uploading a ZIP containing images, the images are not shown afterwards. They seem to be uploaded and extracted in the album having their original names (not as Batch Import which seems to number the images). The album folder contains in my case also a subfolder __MACOSX probably because i created the ZIP on a Mac.

Looks to me like the extracted images are not saved/linked correctly in the database.

**Comment by nd2s** [comment]
they are not saved at all in the db...

**Comment by splittingred** [comment]
Anything in your core/cache/logs/error.log file?

**Comment by nd2s** [comment]
I'm afraid there is nothing.

**Comment by nd2s** [comment]
I installed it on another system. On the first day it worked, but now the same (and I haven't changed anything).

In the zipupload.php processor, around line 100 there is "if ($dir->isDir()) {", which never gets true.
The files are in the /file/id/ folder with their original names, db entries are not created.

And there are still no errors.

**Comment by nd2s** [comment]
The problem is that you have to zip a _folder_. If you just compress some images directly they are only copied  which generates a lot of inaccessible and unusable files.

Could you please fix that?

**Comment by lithiumlab** [comment]
The way to .zip a folder should be clarified in the official documentation of this Extra.
Maybe this page: http://rtfm.modx.com/display/ADDON/Gallery.Setting+Up+Your+Gallery

Zip upload doesn't work for me either way. No erros in the console. Tried with 2.0.8-pl, 2.1.0-RC1 and 2.1.0-RC3
Using Windows XP 2003 server

**Comment by nd2s** [comment]
My ugly temporarily solution: http://pastebin.com/wsQ0289y

Sry I did not post the whole file, because I would not work for you due to several modifications I made. Just replace this part and it _should_ add files from / and /dirs to your gallery.

**Comment by eerne** [comment]
Could you fork, commit, push? That way well see a nice diff on github. Of corse github lets you also send pull-request if you want your changes to go into upstream.
