### ISSUE TITLE
getPage navigation not showing up when used with Gallery

### ISSUE THREAD

**Issue by kenquad** [splittingred/Gallery#87]
Please see this forum thread: http://modxcms.com/forums/index.php/topic,62986.0.html

Basically, getPage is limiting the number of gallery entries on a page, but no navigation element is showing up.   To make sure my page.nav placeholder was working, I changed the getPage source to getResources rather than Gallery, and it worked fine.

**Comment by splittingred** [comment]
Use &totalVar=`gallery.total` in your getPage call.

**Comment by moniarde** [comment]
I'm having the same issue with this - [[+gallery.total]] is coming up empty. I've just upgraded to Gallery 1.4.0 and getPage 1.2.1. Here's my snippet call, this is all that's on the page.

`[[!getPage ? &element=`gallery` &album=`Test gallery` &albumRequestVar=`[Test gallery]` &limit=`12` &totalVar=`[[+gallery.total]]`]]
<div class="pageNav">[[!+page.nav]]</div>`
