### ISSUE TITLE
GalleryAlbums snippet doesn't do anything.

### ISSUE THREAD

**Issue by soopermuse** [splittingred/Gallery#9]
Greetings, I am using Gallery with ModX Revolution RC3 and seem to be unable to get the GalleryAlbums snippet to work.  Both when implimenting it manually, and when using your example gallery code.

All other functions/snippets work fine, however GalleryAlbums just doesn't render anything. :(

**Comment by splittingred** [comment]
Have you made sure that your albums are both "Active" and "Prominent"?

**Comment by soopermuse** [comment]
Ah, I had accidentally unticked prominent on my test album, my apologies.  Thanks for the assist. :)
