### ISSUE TITLE
Javascript error when creating a gallery

### ISSUE THREAD

**Issue by w3d2nl** [splittingred/Gallery#90]
### Occurring:

When I try to create a new gallery I fill in the details and click 'Save'. Then the progressbar shows up and disappears almost immediately. Then my browser (FF 4.0) notifies me about an error. I get a Javascript error saying:
### Error:

A is undefined
Source: http://vdzszw.w3d2.nl/manager/assets/modext/build/core/modx-min.js
Rule: 1
### Using:

MODx Revolution v2.0.8-pl (traditional)
Gallery v1.2.0 rc1
Firefox v4.0
### Question:

Normally I have a clue where to search and debug or fix an error. Now I don't. However, could it have to do with my jQuery version?
Does anyone else have this issue? And how can I fix this?

**Comment by splittingred** [comment]
Ensure you have mod_security off.
