### ISSUE TITLE
Output header error msg in Log

### ISSUE THREAD

**Issue by jgulledge19** [splittingred/Gallery#93]
FYI - From my error log:

OutputThumbnail() failed - headers already sent in file "phpthumb.class.php" on line 3647
[2011-05-06 14:02:40](ERROR @ /assets/components/gallery/connector.php) [Gallery] Error outputting thumbnail:
phpThumb() v1.7.9-200712090829

PHP 5.3, IIS7, MySQL 5.5, Revo2.1RC4

**Comment by splittingred** [comment]
Ensure your paths are correct (check gallery System Settings).
