### ISSUE TITLE
GalleryItem output customization

### ISSUE THREAD

**Issue by Neon4eg** [splittingred/Gallery#98]
It`ll be very good to have ability to set parameters of output image like:
- forced image dimensions
- crop mode (according to forced dimensions)
- jpeg quality
  etc.

**Comment by splittingred** [comment]
All avail through &thumbProperties and &imageProperties, which you can pass in JSON format:

<pre>
&thumbProperties=`{"q":"90","w":"100"}`</pre>


etc...
